services:
  jenkins:
    image: jenkins/jenkins:lts-alpine-jdk21
    container_name: jenkins-server
    restart: on-failure
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080

volumes:
  jenkins_home:
